# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wietse M. Boon
email:
description: >- # this means to ignore newlines until "baseurl:"
  Wietse M. Boon's personal homepage
twitter_username: username
github_username: wmboon
minimal_mistakes_skin: air
search: true
masthead_title: "Personal homepage"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 12 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Wietse M. Boon"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Mathematician"
  links:
    - label: "Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=L1kfNQ0AAAAJ&hl=en"
    - label: "ORCiD"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-4080-2369"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/wietse-boon-58424687"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wmboon"
    - label: "PyGeoN"
      icon: "fas fa-fw fa-feather-alt"
      url: "https://github.com/compgeo-mox/pygeon"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    - label: "Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=L1kfNQ0AAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

collections:
  midirom_papers:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
  # _midirom_papers
  - scope:
      path: ""
      type: midirom_papers
    values:
      layout: single
      author_profile: false
      classes: wide
      share: false
      show_date: false
      header:
        show_overlay_excerpt: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

github: [metadata]